;;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Base: 10 -*

(in-package :kenzo-test-9)

(in-suite :kenzo)

(when (or (string= (package-name (find-package 'cat)) "CAT-7")
          (string= (package-name (find-package 'cat)) "CAT-8"))
  (test smgr-fibration
      (cat-9:cat-9-init)
      (let* ((k1 (cat-9:k-z-1))
             (tw (cat-9:smgr-fibration k1))
             (k2 (cat-9:sorc tw))
             (tt (cat-9:fibration-total tw))
             (gmsm (cat-9:crpr 0 (cat-9:gbar 4 0 '(10 11 12) 0 '(20 21)
                                         0 '(30) 0 '())
                             0 '(2 4 6 8)))
             (br (cat-9:brown-reduction tw))
             (tw-pr (cat-9:bcc br)))
        (dotimes (i 5)
          (print (cat-9:face tt i 4 gmsm)))
        (cat-9:? tw-pr 4 (cat-9:tnpr 4 (cat-9:gbar 4 0 '(1 10 100) 0 '(1000 10000)
                                             0 '(100000) 0 '())
                                 0 '()))))

  (test smgr-crts-contraction
        (cat-9:cat-9-init)
        (let* ((chi (cat-9:smgr-crts-contraction (cat-9:k-z-1)))
               (rdct (cat-9:build-rdct :f (cat-9:zero-mrph (cat-9:sorc chi)
                                                       (cat-9:z-chcm))
                                     :g (cat-9:zero-mrph (cat-9:z-chcm)
                                                       (cat-9:sorc chi))
                                     :h chi)))
          (cat-9:pre-check-rdct rdct)
          (setf cat-9:*tc* (cat-9:cmbn 0 1 (cat-9:crpr 0 cat-9:+null-gbar+ 0 '())))
          (setf cat-9:*bc* (cat-9:cmbn 0 1 :z-gnrt))
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 1 1 (cat-9:crpr 1 cat-9:+null-gbar+ 0 '(1))))
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 4 1 (cat-9:crpr 0 (cat-9:gbar 4 0 '(10 11 12)
                                                             0 '(20 21)
                                                             0 '(30) 0 '())
                                                 0 '(2 4 6 8))))
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 3 1 (cat-9:crpr 0 (cat-9:gbar 3 0 '(10 11)
                                                             0 '(20) 0 '())
                                                 0 '(2 4 6))))
          (check-rdct)))

  (test smgr-tnpr-contraction
        (cat-9:cat-9-init)
        (let* ((chi (cat-9:smgr-tnpr-contraction (cat-9:k-z-1)))
               (rdct (cat-9:build-rdct :f (cat-9:zero-mrph (cat-9:sorc chi)
                                                       (cat-9:z-chcm))
                                     :g (cat-9:zero-mrph (cat-9:z-chcm)
                                                       (cat-9:sorc chi))
                                     :h chi)))
          (cat-9:pre-check-rdct rdct)
          (setf cat-9:*tc* (cat-9:cmbn 0 1 (cat-9:tnpr 0 cat-9:+null-gbar+ 0 '())))
          (setf cat-9:*bc* (cat-9:cmbn 0 1 :z-gnrt))
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 1 1 (cat-9:tnpr 0 cat-9:+null-gbar+ 1 '(1))))
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 3 1 (cat-9:tnpr 0 cat-9:+null-gbar+
                                                 3 '(1 10 100))))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 3 1 (cat-9:tnpr 2 (cat-9:gbar 2 0 '(1) 0 '())
                                                 1 '(10))))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 3 1 (cat-9:tnpr 3 (cat-9:gbar 3 0 '(1 10)
                                                             0 '(100) 0 '())
                                                 0 '())))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 4 1 (cat-9:tnpr 0 cat-9:+null-gbar+
                                                 4 '(1 10 100 1000))))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 4 1 (cat-9:tnpr 2 (cat-9:gbar 2 0 '(1) 0 '())
                                                 2 '(10 100))))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 4 1 (cat-9:tnpr 3 (cat-9:gbar 3 0 '(1 10)
                                                             0 '(100) 0 '())
                                                 1 '(1000))))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct)
          (setf cat-9:*tc* (cat-9:cmbn 4 1 (cat-9:tnpr 4 (cat-9:gbar 4 0 '(1 10 100)
                                                             0 '(1000 10000)
                                                             0 '(100000)
                                                             0 '())
                                                 0 '())))
          (cat-9:? chi cat-9:*tc*)
          (check-rdct))))
