;;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Base: 10 -*

(in-package :kenzo-test-8)

(in-suite :kenzo-8)


(test smgr-fibration
      (cat-8:cat-init)
      (let* ((k1 (cat-8:k-z-1))
             (tw (cat-8:smgr-fibration k1))
             (k2 (cat-8:sorc tw))
             (tt (cat-8:fibration-total tw))
             (gmsm (cat-8:crpr 0 (cat-8:gbar 4 0 '(10 11 12) 0 '(20 21)
                                             0 '(30) 0 '())
                               0 '(2 4 6 8)))
             (br (cat-8:brown-reduction tw))
             (tw-pr (cat-8:bcc br)))
        (dotimes (i 5)
          (print (cat-8:face tt i 4 gmsm)))
        (cat-8:? tw-pr 4 (cat-8:tnpr 4 (cat-8:gbar 4 0 '(1 10 100) 0 '(1000 10000)
                                                   0 '(100000) 0 '())
                                     0 '()))))

(test smgr-crts-contraction
      (cat-8:cat-init)
      (let* ((chi (cat-8:smgr-crts-contraction (cat-8:k-z-1)))
             (rdct (cat-8:build-rdct :f (cat-8:zero-mrph (cat-8:sorc chi)
                                                         (cat-8:z-chcm))
                                     :g (cat-8:zero-mrph (cat-8:z-chcm)
                                                         (cat-8:sorc chi))
                                     :h chi)))
        (cat-8:pre-check-rdct rdct)
        (setf cat-8:*tc* (cat-8:cmbn 0 1 (cat-8:crpr 0 cat-8:+null-gbar+ 0 '())))
        (setf cat-8:*bc* (cat-8:cmbn 0 1 :z-gnrt))
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 1 1 (cat-8:crpr 1 cat-8:+null-gbar+ 0 '(1))))
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 4 1 (cat-8:crpr 0 (cat-8:gbar 4 0 '(10 11 12)
                                                                   0 '(20 21)
                                                                   0 '(30) 0 '())
                                                     0 '(2 4 6 8))))
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 3 1 (cat-8:crpr 0 (cat-8:gbar 3 0 '(10 11)
                                                                   0 '(20) 0 '())
                                                     0 '(2 4 6))))
        (check-rdct)))

(test smgr-tnpr-contraction
      (cat-8:cat-init)
      (let* ((chi (cat-8:smgr-tnpr-contraction (cat-8:k-z-1)))
             (rdct (cat-8:build-rdct :f (cat-8:zero-mrph (cat-8:sorc chi)
                                                         (cat-8:z-chcm))
                                     :g (cat-8:zero-mrph (cat-8:z-chcm)
                                                         (cat-8:sorc chi))
                                     :h chi)))
        (cat-8:pre-check-rdct rdct)
        (setf cat-8:*tc* (cat-8:cmbn 0 1 (cat-8:tnpr 0 cat-8:+null-gbar+ 0 '())))
        (setf cat-8:*bc* (cat-8:cmbn 0 1 :z-gnrt))
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 1 1 (cat-8:tnpr 0 cat-8:+null-gbar+ 1 '(1))))
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 3 1 (cat-8:tnpr 0 cat-8:+null-gbar+
                                                     3 '(1 10 100))))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 3 1 (cat-8:tnpr 2 (cat-8:gbar 2 0 '(1) 0 '())
                                                     1 '(10))))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 3 1 (cat-8:tnpr 3 (cat-8:gbar 3 0 '(1 10)
                                                                   0 '(100) 0 '())
                                                     0 '())))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 4 1 (cat-8:tnpr 0 cat-8:+null-gbar+
                                                     4 '(1 10 100 1000))))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 4 1 (cat-8:tnpr 2 (cat-8:gbar 2 0 '(1) 0 '())
                                                     2 '(10 100))))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 4 1 (cat-8:tnpr 3 (cat-8:gbar 3 0 '(1 10)
                                                                   0 '(100) 0 '())
                                                     1 '(1000))))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)
        (setf cat-8:*tc* (cat-8:cmbn 4 1 (cat-8:tnpr 4 (cat-8:gbar 4 0 '(1 10 100)
                                                                   0 '(1000 10000)
                                                                   0 '(100000)
                                                                   0 '())
                                                     0 '())))
        (cat-8:? chi cat-8:*tc*)
        (check-rdct)))
